=== firak01/Projekt_Kernel02_JAZLanguageMarkup/JAZLanguageMarkup/test/zKernel/xml/reader/gamecard.dtd
<!ELEMENT ursuppe (genecard+)>
<!--Kommentar: Die Reihenfolge der Attribute ist nicht beliebig -->
<!ELEMENT genecard (alias, name, description?,grafik?)>
<!ELEMENT alias (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!--Kommentar: die Beschreibung -->
<!ELEMENT description (#PCDATA)>
<!--Kommentar: die Position und der Dateiname eines Bilds -->
<!ELEMENT grafik (uri)>
<!ELEMENT uri (file, filepathrelative)>
<!ELEMENT file (#PCDATA)> 
<!ELEMENT filepathrelative (#PCDATA)>

=== firak01/Projekt_Kernel02_JAZLanguageMarkup/JAZLanguageMarkup/test/zKernel/xml/reader/ursuppe.xml
<?xml version="1.0" ?>
<!DOCTYPE ursuppe SYSTEM "gamecard.dtd">
<ursuppe>
	<genecard>
		<alias>1</alias>
		<name>blablab</name>
		<description>die erste Karte</description>
		<grafik>
			<uri>
				<file>eins.jpg</file>
				<filepathrelative>filezzz</filepathrelative>
			</uri>
		</grafik>
	</genecard>
	<genecard>
		<alias>2</alias>
		<name>blablab2</name>
		<description>die zweite Karte</description>
	</genecard>
	<genecard>
		<alias>3</alias>
		<name>blablab3</name>
		<description>die dritte Karte</description>
	</genecard>
</ursuppe>
