=== firak01/Projekt_Kernel02_JAZLanguageMarkup/JAZLanguageMarkup/test/zKernel/xml/reader/gamecard.xsd
<?xml version="1.0" encoding="iso-8859-1"?>
<xsd:schema xmlns:xsd=="http://www.w3.org/XMLSchema">
<xsd:element name="ursuppe">
 <xsd:complexType>
  <xsd:sequence>
   <xsd:element name="genecard" maxOccurs="unbounded"/>
    <xsd:complexType>
     <xsd:sequence>
      <xsd:element name="alias" type="xsd:string" minOccurs="1" maxOccurs="1"/>
      <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/> 
     </xsd:sequence>
    </xsd:complexType>
   </xsd:sequence>
  </xsd:complexType> 
 </xsd:element>
</xsd:schema>

=== firak01/Projekt_Kernel02_JAZLanguageMarkup/JAZLanguageMarkup/test/zKernel/xml/reader/ursuppe mit verweis auf xsd.xml
<?xml version="1.0" ?>
<ursuppe xmlns:xsi="http://www.w3.org/XMLSchema-instance" xsi:noNamespaceSchemaLocation="gamecard.xsd">
	<genecard>
		<alias>das ist ein Test</alias>
		<name>blablab</name>
	</genecard>
	<genecard>
		<alias>das ist ein Test2</alias>
		<alias>das ist ein Test3</alias>
		<name>blablab2</name>
	</genecard>
</ursuppe>
